// generated by cdktf get
// sourcegraph/executors/aws//modules/networking
import { TerraformModule, TerraformModuleUserConfig } from 'cdktf';
import { Construct } from 'constructs';
export interface ExecutorsNetworkingConfig extends TerraformModuleUserConfig {
  /**
   * The availability zone to create the network in.
   */
  readonly availabilityZone: string;
  /**
   * When true, the network will contain a NAT router. Use when executors should not get public IPs.
   */
  readonly nat?: boolean;
  /**
   * Use randomized names for resources. Deployments using the legacy naming convention will be updated in-place with randomized names when enabled.
   */
  readonly randomizeResourceNames: boolean;
  /**
   * An optional prefix to add to all resources created.
   */
  readonly resourcePrefix?: string;
}
/**
 * Defines an ExecutorsNetworking based on a Terraform module
 *
 * Docs at Terraform Registry: {@link https://registry.terraform.io/modules/sourcegraph/executors/aws/~> 5.0.1/submodules/networking sourcegraph/executors/aws//modules/networking}
 */
export class ExecutorsNetworking extends TerraformModule {
  private readonly inputs: { [name: string]: any } = { }
  public constructor(scope: Construct, id: string, config: ExecutorsNetworkingConfig) {
    super(scope, id, {
      ...config,
      source: 'sourcegraph/executors/aws//modules/networking',
      version: '~> 5.0.1',
    });
    this.availabilityZone = config.availabilityZone;
    this.nat = config.nat;
    this.randomizeResourceNames = config.randomizeResourceNames;
    this.resourcePrefix = config.resourcePrefix;
  }
  public get availabilityZone(): string {
    return this.inputs['availability_zone'] as string;
  }
  public set availabilityZone(value: string) {
    this.inputs['availability_zone'] = value;
  }
  public get nat(): boolean | undefined {
    return this.inputs['nat'] as boolean | undefined;
  }
  public set nat(value: boolean | undefined) {
    this.inputs['nat'] = value;
  }
  public get randomizeResourceNames(): boolean {
    return this.inputs['randomize_resource_names'] as boolean;
  }
  public set randomizeResourceNames(value: boolean) {
    this.inputs['randomize_resource_names'] = value;
  }
  public get resourcePrefix(): string | undefined {
    return this.inputs['resource_prefix'] as string | undefined;
  }
  public set resourcePrefix(value: string | undefined) {
    this.inputs['resource_prefix'] = value;
  }
  public get ipCidrOutput() {
    return this.getString('ip_cidr')
  }
  public get natIpOutput() {
    return this.getString('nat_ip')
  }
  public get subnetIdOutput() {
    return this.getString('subnet_id')
  }
  public get vpcIdOutput() {
    return this.getString('vpc_id')
  }
  protected synthesizeAttributes() {
    return this.inputs;
  }
}
